name: Lint code
on:
  push:
    branches:
      - main
jobs:
  docs:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm init -y 
          npm i remarkable

      - name: Build
        run: node deploy.js

      - name: Deploy
        run: |
          git fetch
          git checkout deploy
          git add .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git commit --amend -m "build ${GITHUB_SHA}"
          git push
